### ISSUE TITLE
Missing keys in pretrained VisualBert model

### ISSUE THREAD

**Issue by mmiakashs** [facebookresearch/mmf#569] opened 2020-09-17 23:58 UTC
I was trying to load the pretrained visual_bert model similar to the [snippet is given here](https://github.com/facebookresearch/mmf/issues/465#issuecomment-675876026). However, I was getting missing keys error. Does the visual_bert model class or pretrained model is changed? Or am I missing anything? Thanks

```
RuntimeError: Error(s) in loading state_dict for VisualBERT:
	Missing key(s) in state_dict: "model.bert.additional_layer.attention.self.query.weight", "model.bert.additional_layer.attention.self.query.bias", "model.bert.additional_layer.attention.self.key.weight", "model.bert.additional_layer.attention.self.key.bias", "model.bert.additional_layer.attention.self.value.weight", "model.bert.additional_layer.attention.self.value.bias", "model.bert.additional_layer.attention.output.dense.weight", "model.bert.additional_layer.attention.output.dense.bias", "model.bert.additional_layer.attention.output.LayerNorm.weight", "model.bert.additional_layer.attention.output.LayerNorm.bias", "model.bert.additional_layer.intermediate.dense.weight", "model.bert.additional_layer.intermediate.dense.bias", "model.bert.additional_layer.output.dense.weight", "model.bert.additional_layer.output.dense.bias", "model.bert.additional_layer.output.LayerNorm.weight", "model.bert.additional_layer.output.LayerNorm.bias".
```

**Comment by vedanuj** [comment] 2020-09-18 01:07
This is bug caused by a recent change. We are working on fixing it.

**Comment by mmiakashs** [comment] 2020-09-18 03:15
@vedanuj Thanks, could you please let me know which version can I install to use the pretrained visual_bert during this time?

**Comment by vedanuj** [comment] 2020-09-18 05:25
@mmiakashs Can you try reinstalling mmf from master? The fix has landed.

**Comment by mmiakashs** [comment] 2020-09-18 14:51
@vedanuj Thanks, it is working 😄

**Closed** 2020-09-18 20:08 UTC
