### ISSUE TITLE
Don't have enough hard disk memory for train and test in Colab for MMF

### ISSUE THREAD

**Issue by AMiiR93** [facebookresearch/mmf#671] opened 2020-11-02 09:27 UTC
## ❓ Questions and Help
My Dataset is about 30GB and I think i need 300GB at the end
Colab pro version can help me? or can i connect my google drive memory with Colab?
"""MY Code:
> !git clone https://github.com/ricolike/mmgnn_textvqa
> !cd mmgnn_textvqa && pip install -r requirements.txt

## ERROR: spacy 2.2.4 has requirement tqdm<5.0.0,>=4.38.0, but you'll have tqdm 4.19.9 which is incompatible.
##ERROR: google-colab 1.0.0 has requirement requests~=2.23.0, but you'll have requests 2.21.0 which is incompatible.
##ERROR: fbprophet 0.7.1 has requirement tqdm>=4.36.1, but you'll have tqdm 4.19.9 which is incompatible.
##ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
##ERROR: transformers 3.4.0 has requirement tqdm>=4.27, but you'll have tqdm 4.19.9 which is incompatible.

> %cd mmgnn_textvqa
> !gdown --id 1ieIx4MB49DBm1ycY203f15kvcrX4IoLt
> !mkdir -p data
> !unzip data.zip -d data
"""

**Comment by apsdehal** [comment] 2020-11-02 19:42
hi, @AMiiR93. The issues don't seem to be related to MMF repository and seems to be for a fork for it which we can't support actively.

**Comment by apsdehal** [comment] 2020-11-02 19:44
Closing as duplicate of #672

**Closed by apsdehal** 2020-11-02 19:44 UTC
