### ISSUE TITLE
AssertionError: dev.jsonl doesn't exist in /root/.cache/torch/mmf/data/datasets/hateful_memes/defaults/images

### ISSUE THREAD

**Issue by Katy-katy** [facebookresearch/mmf#887] opened 2021-04-17 21:57 UTC
## ❓ Questions and Help
hello, I am using tutorial https://colab.research.google.com/github/facebookresearch/mmf/blob/notebooks/notebooks/mmf_hm_example.ipynb

But when I run the cell with "!mmf_convert_hm --zip_file /content/hm.zip --password $password --bypass_checksum=1", I got:

`
2021-04-17 21:43:35.622789: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Data folder is /root/.cache/torch/mmf/data
Zip path is /content/hm.zip
Moving /content/hm.zip
Unzipping /content/hm.zip
Extracting the zip can take time. Sit back and relax.
Traceback (most recent call last):
  File "/usr/local/bin/mmf_convert_hm", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/mmf_cli/hm_convert.py", line 165, in main
    converter.convert()
  File "/usr/local/lib/python3.7/dist-packages/mmf_cli/hm_convert.py", line 102, in convert
    self.assert_files(images_path)
  File "/usr/local/lib/python3.7/dist-packages/mmf_cli/hm_convert.py", line 34, in assert_files
    ), f"{file} doesn't exist in {folder}"
AssertionError: dev.jsonl doesn't exist in /root/.cache/torch/mmf/data/datasets/hateful_memes/defaults/images

`
![Screen Shot 2021-04-17 at 2 56 40 PM](https://user-images.githubusercontent.com/7121381/115127677-3696f500-9f8d-11eb-82c9-cacdb17cd7bc.png)

to intall mmf I used: "!pip install --pre --upgrade mmf"
....

**Comment by apsdehal** [comment] 2021-04-20 18:13
Hi,
Thanks for pointing this out. We will investigate this.

**Comment by apsdehal** [comment] 2021-04-20 18:14
Closing this as duplicate of #886

**Closed by apsdehal** 2021-04-20 18:14 UTC
Labels: bug, needs reproduction, triaged

**Comment by AnjumJ123** [comment] 2022-04-21 08:53
> ## ❓ Questions and Help
> hello, I am using tutorial https://colab.research.google.com/github/facebookresearch/mmf/blob/notebooks/notebooks/mmf_hm_example.ipynb
> 
> But when I run the cell with "!mmf_convert_hm --zip_file /content/hm.zip --password $password --bypass_checksum=1", I got:
> 
> ` 2021-04-17 21:43:35.622789: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0 Data folder is /root/.cache/torch/mmf/data Zip path is /content/hm.zip Moving /content/hm.zip Unzipping /content/hm.zip Extracting the zip can take time. Sit back and relax. Traceback (most recent call last): File "/usr/local/bin/mmf_convert_hm", line 8, in sys.exit(main()) File "/usr/local/lib/python3.7/dist-packages/mmf_cli/hm_convert.py", line 165, in main converter.convert() File "/usr/local/lib/python3.7/dist-packages/mmf_cli/hm_convert.py", line 102, in convert self.assert_files(images_path) File "/usr/local/lib/python3.7/dist-packages/mmf_cli/hm_convert.py", line 34, in assert_files ), f"{file} doesn't exist in {folder}" AssertionError: dev.jsonl doesn't exist in /root/.cache/torch/mmf/data/datasets/hateful_memes/defaults/images
> 
> ` ![Screen Shot 2021-04-17 at 2 56 40 PM](https://user-images.githubusercontent.com/7121381/115127677-3696f500-9f8d-11eb-82c9-cacdb17cd7bc.png)
> 
> to intall mmf I used: "!pip install --pre --upgrade mmf" ....

Hi, were you able to find the fix to this issue? I am facing the same problem when trying to run mmf_run config for hateful_meme train dataset on VisualBERT pretrained model from MMF.
