### ISSUE TITLE
Issue with Training command

### ISSUE THREAD

**Issue by nbhalla93** [facebookresearch/mmf#681] opened 2020-11-12 01:25 UTC
## ❓ Questions and Help

**Ran this command fro training:** 
mmf_run config=projects/m4c/configs/textvqa/defaults.yaml \
    datasets=textvqa \
    model=m4c \
    run_type=train_val \
    training.batch_size=16 \
    training.update_frequency=2

**got this error:**
**I am not able to understand the error here.**

![Screen Shot 2020-11-11 at 8 20 15 PM (2)](https://user-images.githubusercontent.com/19534655/98883088-c45d3a00-245b-11eb-8a44-0645175d7c05.png)

<img width="1164" alt="Screen Shot 2020-11-11 at 8 24 32 PM" src="https://user-images.githubusercontent.com/19534655/98883142-ed7dca80-245b-11eb-8397-0be6692f600a.png">

**Comment by vedanuj** [comment] 2020-11-12 02:58
Can you retry with training.num_workers=0? That might give a better error log.

**Comment by apsdehal** [comment] 2020-11-19 03:25
This is happening probably due to memory issues. Closing this as duplicate of #680 as that one has better details as suggestions.

**Closed by apsdehal** 2020-11-19 03:25 UTC
