### ISSUE TITLE
Size mismatch for testing movie_mcan

### ISSUE THREAD

**Issue by mokadyr** [facebookresearch/mmf#484] opened 2020-08-17 19:58 UTC
## 🐛 Bug

`-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/private/home/mokady/.conda/envs/det2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/private/home/mokady/mokady_intern2/mmf/mmf_cli/run.py", line 66, in distributed_main
    main(configuration, init_distributed=True, predict=predict)
  File "/private/home/mokady/mokady_intern2/mmf/mmf_cli/run.py", line 54, in main
    trainer.inference()
  File "/private/home/mokady/mokady_intern2/mmf/mmf/trainers/mmf_trainer.py", line 123, in inference
    self.prediction_loop(dataset)
  File "/private/home/mokady/mokady_intern2/mmf/mmf/trainers/core/evaluation_loop.py", line 62, in prediction_loop
    for batch in tqdm.tqdm(dataloader):
  File "/private/home/mokady/.conda/envs/det2/lib/python3.8/site-packages/tqdm/std.py", line 1130, in __iter__
    for obj in iterable:
  File "/private/home/mokady/.conda/envs/det2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/private/home/mokady/.conda/envs/det2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/private/home/mokady/.conda/envs/det2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/private/home/mokady/.conda/envs/det2/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/private/home/mokady/.conda/envs/det2/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/private/home/mokady/.conda/envs/det2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/private/home/mokady/.conda/envs/det2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/private/home/mokady/.conda/envs/det2/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 207, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/private/home/mokady/mokady_intern2/mmf/mmf/datasets/builders/vqa2/dataset.py", line 49, in __getitem__
    return self.load_item(idx)
  File "/private/home/mokady/mokady_intern2/mmf/mmf/datasets/builders/vqa2/dataset.py", line 85, in load_item
    features = self.features_db[idx]
  File "/private/home/mokady/mokady_intern2/mmf/mmf/datasets/databases/features_database.py", line 91, in __getitem__
    return self.get(image_info)
  File "/private/home/mokady/mokady_intern2/mmf/mmf/datasets/databases/features_database.py", line 99, in get
    return self.from_path(feature_path)
  File "/private/home/mokady/mokady_intern2/mmf/mmf/datasets/databases/features_database.py", line 107, in from_path
    features, infos = self._get_image_features_and_info(path)
  File "/private/home/mokady/mokady_intern2/mmf/mmf/datasets/databases/features_database.py", line 80, in _get_image_features_and_info
    image_feats, infos = self._read_features_and_info(feat_file)
  File "/private/home/mokady/mokady_intern2/mmf/mmf/datasets/databases/features_database.py", line 65, in _read_features_and_info
    feature, info = feature_reader.read(feat_file)
  File "/private/home/mokady/mokady_intern2/mmf/mmf/datasets/databases/readers/feature_readers.py", line 81, in read
    return self.feat_reader.read(image_feat_path)
  File "/private/home/mokady/mokady_intern2/mmf/mmf/datasets/databases/readers/feature_readers.py", line 103, in read
    padded_feat[:, :, : h * w] = feat
RuntimeError: The expanded size of the tensor (608) must match the existing size (1024) at non-singleton dimension 2.  Target sizes: [1, 2048, 608].  Tensor sizes: [2048, 1024]`

## Command

`mmf_predict config=projects/movie_mcan/configs/vqa2/defaults.yaml dataset=vqa2 model=movie_mcan run_type=test checkpoint.resume_zoo=movie_mcan.grid.vqa2_vg env.cache_dir=./mmf0/ env.save_dir=./mmf0/`

## To Reproduce

`mmf_predict config=projects/movie_mcan/configs/vqa2/defaults.yaml dataset=vqa2 model=movie_mcan run_type=test checkpoint.resume_zoo=movie_mcan.grid.vqa2_vg env.cache_dir=./mmf0/ env.save_dir=./mmf0/`

**Comment by apsdehal** [comment] 2020-08-17 21:04
We are aware of this. Marking this as duplicate of #453. @vedanuj  Have a look whenever you get time.

**Closed** 2020-08-19 00:14 UTC
