### ISSUE TITLE
How to run mmf_config using python 3.7

### ISSUE THREAD

**Issue by ambuje** [facebookresearch/mmf#433] opened 2020-07-27 13:57 UTC
## ❓ Questions and Help
Is there any specific command for mmf_config where I can mention to run the code using python3.7. 
I am having python3.6 and 3.7 both and facing some issues to make python 3.7 default. If there exists a command where  I can specify python3.7 do let me know. 

Thanks

**Comment by vedanuj** [comment] 2020-07-27 14:39
Hi @ambuje there is no command mmf_config. We cannot choose python version using config. One possible way is you can create a condo environment specifying which Python version you want and run mmf inside that.

**Comment by apsdehal** [comment] 2020-07-31 21:59
Closing as this is out of scope for MMF. The issue is related to the setup of user and conda should be used to properly setup python versions. Please open up a new issue if you face more problem. Thanks.

**Closed by apsdehal** 2020-07-31 21:59 UTC

**Comment by Ifrahmaqsood** [comment] 2021-01-30 11:04
> ## ❓ Questions and Help
> Is there any specific command for mmf_config where I can mention to run the code using python3.7.
> I am having python3.6 and 3.7 both and facing some issues to make python 3.7 default. If there exists a command where I can specify python3.7 do let me know.
> 
> Thanks

Have you been able to resolve this issue? I want to use it with python 3.6 .I am using Ubuntu server which has many users and python versions and i already have many packages installed in python3.6 folder. If i don't want to use conda environment what else could be the possible solution?
